// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {beamsync} from '../models';

export function ApproveTransfer(arg1:string):Promise<void>;

export function GetReceivedFiles():Promise<Array<main.ReceivedFile>>;

export function GetSavePath():Promise<string>;

export function GetTransferSettings():Promise<beamsync.TransferSettings>;

export function OpenFile(arg1:string):Promise<string>;

export function PlaySound(arg1:string):Promise<void>;

export function RejectTransfer(arg1:string):Promise<void>;

export function ResetApp():Promise<void>;

export function SaveTransferSettings(arg1:beamsync.TransferSettings):Promise<string>;

export function SetSavePath():Promise<string>;

export function StartReceiver():Promise<string>;

export function StartReceiverDefault():Promise<string>;

export function StartSender():Promise<string>;

export function StopReceiver():Promise<string>;

export function StopSender():Promise<string>;
